name: Build and Deploy Catalog

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect project directory
        id: detect
        shell: bash
        run: |
          set -eux
          for d in . catalog_builder catalog_builder_flat_root; do
            if [ -f "$d/requirements.txt" ] && [ -f "$d/build.py" ]; then
              echo "WORKDIR=$d" >> "$GITHUB_ENV"
              echo "Detected WORKDIR: $d"
              exit 0
            fi
          done
          CAND=$(find . -maxdepth 3 -type f -name requirements.txt | sed 's|/requirements.txt$||' | head -n1 || true)
          if [ -n "$CAND" ] && [ -f "$CAND/build.py" ]; then
            echo "WORKDIR=$CAND" >> "$GITHUB_ENV"
            echo "Detected WORKDIR via find: $CAND"
          else
            echo "requirements.txt or build.py not found" >&2
            echo "Repository tree:"
            ls -laR | head -n 500
            exit 1
          fi

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show tree
        run: |
          echo "Using WORKDIR=${{ env.WORKDIR }}"
          ls -la "${{ env.WORKDIR }}"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles(format('{0}/requirements.txt', env.WORKDIR)) }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -V
          pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ env.WORKDIR }}

      - name: Fetch images
        run: |
          python scrape_images.py --limit 120 || echo "Image scraper failed, continuing..."
        working-directory: ${{ env.WORKDIR }}

      - name: Build catalog
        run: python build.py --title "Route 66 Guns & Ammo Catalog" --min_stock 1
        working-directory: ${{ env.WORKDIR }}

      - name: Disable Jekyll
        run: |
          mkdir -p out
          touch out/.nojekyll
        working-directory: ${{ env.WORKDIR }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.WORKDIR }}/out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
